a:
	g++ -shared -fPIC -g -o aNativeLib.so NativeLib.cpp  genProofFun.cpp CJsonObject.cpp cJSON.c  -D_LINUX_OS_ -I /usr/java/jdk1.8.0_181-amd64/include -I /usr/java/jdk1.8.0_181-amd64/include/linux  -L /usr/local/lib libcryptopp.a
