/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whu_jni_NativeLib */

#ifndef _Included_com_whu_jni_NativeLib
#define _Included_com_whu_jni_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whu_jni_NativeLib
 * Method:    generateUUID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_whu_jni_NativeLib_generateUUID
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_whu_jni_NativeLib_genProof
  (JNIEnv *, jclass , jstring position);

#ifdef __cplusplus
}
#endif
#endif
