
# server config info
server:
  port: 8083
#  servlet:
#    context-path: /PoL
# spring config info
spring:
#  #datasource druid
#  datasource:
#    name: bootssm
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid: #druid config
#      url: jdbc:mysql://localhost:3306/nj-1901-pro?serverTimezone=GMT%2B8
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#      filters: stat
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
  # template config info
  thymeleaf:
    cache: false # default true
    mode: LEGACYHTML5  # nekohtml
  swagger:
    enabled: true
#    title: 文档
#    description: API文档
#    version: v2.0.5
#    contact:
#      name: boxiao
    base-package: com.whu
#    security:
#      filter-plugin: false
#      username: boxiao
#      password: zhou

# mybatis spring config
#mybatis:
#  type-aliases-package: com.whu.bean
#  mapper-locations: classpath:com/whu/mapper/*.xml
# log config info
logging:
  config: classpath:log4j2.xml
  level:
    com.whu: info

# spring boot dubbo
dubbo:
  application:
    name: boot-user-service
  registry:
    address: zookeeper://202.114.114.46:2181
  protocol:
    name: dubbo
    port: 20880


